### PR TITLE
Fix README typos.

### PR DESCRIPTION
**Pull request by jonthegeek**
Is it still true that {luz} shouldn't be used for anything meaningful yet?

### CODE REVIEW

**Comment by jonthegeek** [comment]
Converted to draft. I see related typos in at least one vignette, gonna submit them all as one PR.

**Comment by dfalbel** [comment]
I think we can remove that phrase:

>  shouldn't be used for anything meaningful yet?

**Comment by jonthegeek** [comment]
I'm running into some issues trying to update examples. I'm logging them here before creating separate tickets:

- `dogs-vs-cats-binary-classification.Rmd`: The `torchdatasets` help for this points to a function for a legacy API. I downloaded a new kaggle.json from kaggle, but I don't know if it has a version issue or I don't have proper access or what, but I can't download the dataset. Therefore I can't check the rest of the vignette.
- `fit` results in an R-bomb in each vignette! I'm exploring whether this is a general issue, but I know for sure `torch` itself works fine (I fit a model earlier today without incident).

These issues don't directly relate to this update, so I'm submitting the PR before fully debugging, I just didn't want to forget.

**Comment by dfalbel** [comment]
Thank you very much @jonthegeek !

**Pull request merged**
